<?php
declare(strict_types=1);
requireRole('subject-officer');
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/activity.php';
require_once __DIR__.'/../../includes/prohibited-item-selector.php';
$activePage='eligibility-rules';$db=database();$errors=[];$ruleId=filter_input(INPUT_GET,'rule_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'rule_id',FILTER_VALIDATE_INT);
if(!$ruleId){http_response_code(404);exit('Eligibility rule not found.');}

// Save the optional beneficiary field with the editable item rule, not as a separate hard-coded item setting.
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='save-rule-with-detail'){
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired. Refresh and try again.';
 else try{
  $disability=filter_input(INPUT_POST,'disability_type_id',FILTER_VALIDATE_INT);$name=preg_replace('/\s+/',' ',trim((string)($_POST['item_name']??'')));$variety=preg_replace('/\s+/',' ',trim((string)($_POST['variety']??'')));$value=filter_input(INPUT_POST,'restriction_value',FILTER_VALIDATE_INT);$unit=(string)($_POST['restriction_unit']??'');$blocked=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['prohibited_item_ids']??[])))));$needsDetail=(string)($_POST['beneficiary_detail_required']??'0')==='1';$detailLabel=preg_replace('/\s+/',' ',trim((string)($_POST['beneficiary_detail_label']??'')));$detailType=(string)($_POST['beneficiary_detail_type']??'text');
  if(!$disability||mb_strlen($name)<2||mb_strlen($name)>100)throw new RuntimeException('Enter a valid disability and item name.');if($value===false||$value<0||$value>100||!in_array($unit,['months','years'],true))throw new RuntimeException('Enter a valid probation period and unit.');if($needsDetail&&(mb_strlen($detailLabel)<2||mb_strlen($detailLabel)>100||!in_array($detailType,['text','number'],true)))throw new RuntimeException('Enter a valid beneficiary information field name and type.');$months=$unit==='years'?$value*12:$value;
  $db->beginTransaction();$q=$db->prepare('SELECT item_id FROM disability_aid_items WHERE id=:id FOR UPDATE');$q->execute(['id'=>$ruleId]);$itemId=(int)$q->fetchColumn();if(!$itemId)throw new RuntimeException('The eligibility rule no longer exists.');$q=$db->prepare("SELECT id FROM disability_types WHERE id=:id AND status='active'");$q->execute(['id'=>$disability]);if(!$q->fetchColumn())throw new RuntimeException('The selected disability type is unavailable.');$db->prepare('UPDATE inventory_items SET item_name=:name,variety=:variety WHERE id=:id')->execute(['name'=>$name,'variety'=>$variety,'id'=>$itemId]);$db->prepare("UPDATE disability_aid_items SET disability_type_id=:disability,restriction_months=:months,beneficiary_field_label=:label,beneficiary_field_type=:type,status='active' WHERE id=:id")->execute(['disability'=>$disability,'months'=>$months,'label'=>$needsDetail?$detailLabel:null,'type'=>$detailType,'id'=>$ruleId]);$db->prepare('DELETE FROM disability_item_prohibitions WHERE disability_aid_item_id=:id')->execute(['id'=>$ruleId]);$add=$db->prepare('INSERT INTO disability_item_prohibitions(disability_aid_item_id,prohibited_item_id) VALUES(:rule,:item)');foreach($blocked as $blockedItem)if($blockedItem!==$itemId)$add->execute(['rule'=>$ruleId,'item'=>$blockedItem]);$db->commit();logActivity('Disability Aid Configuration','Updated item rule and beneficiary field','RULE-'.$ruleId);$_SESSION['flash_success']='Eligibility rule updated.';unset($_SESSION['csrf_token']);header('Location: dashboard.php?page=eligibility-rules');exit;
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to update the eligibility rule.';}
}

if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')!=='save-rule-with-detail'){
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired. Refresh and try again.';
 else try{
  $disability=filter_input(INPUT_POST,'disability_type_id',FILTER_VALIDATE_INT);$name=preg_replace('/\s+/',' ',trim((string)($_POST['item_name']??'')));$variety=preg_replace('/\s+/',' ',trim((string)($_POST['variety']??'')));$value=filter_input(INPUT_POST,'restriction_value',FILTER_VALIDATE_INT);$unit=(string)($_POST['restriction_unit']??'');$blocked=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['prohibited_item_ids']??[])))));
  if(!$disability||mb_strlen($name)<2||mb_strlen($name)>100)throw new RuntimeException('Enter a valid disability and item name.');if($value===false||$value<0||$value>100||!in_array($unit,['months','years'],true))throw new RuntimeException('Enter a valid probation period and unit.');$months=$unit==='years'?$value*12:$value;
  $db->beginTransaction();$q=$db->prepare('SELECT item_id FROM disability_aid_items WHERE id=:id FOR UPDATE');$q->execute(['id'=>$ruleId]);$itemId=(int)$q->fetchColumn();if(!$itemId)throw new RuntimeException('The eligibility rule no longer exists.');
  $q=$db->prepare("SELECT id FROM disability_types WHERE id=:id AND status='active'");$q->execute(['id'=>$disability]);if(!$q->fetchColumn())throw new RuntimeException('The selected disability type is unavailable.');
  $db->prepare('UPDATE inventory_items SET item_name=:name,variety=:variety WHERE id=:id')->execute(['name'=>$name,'variety'=>$variety,'id'=>$itemId]);
  $db->prepare("UPDATE disability_aid_items SET disability_type_id=:disability,restriction_months=:months,status='active' WHERE id=:id")->execute(['disability'=>$disability,'months'=>$months,'id'=>$ruleId]);
  $db->prepare('DELETE FROM disability_item_prohibitions WHERE disability_aid_item_id=:id')->execute(['id'=>$ruleId]);$add=$db->prepare('INSERT INTO disability_item_prohibitions(disability_aid_item_id,prohibited_item_id) VALUES(:rule,:item)');foreach($blocked as $blockedItem)if($blockedItem!==$itemId)$add->execute(['rule'=>$ruleId,'item'=>$blockedItem]);
  $db->commit();logActivity('Disability Aid Configuration','Updated full eligibility rule','RULE-'.$ruleId);$_SESSION['flash_success']='Eligibility rule updated.';unset($_SESSION['csrf_token']);header('Location: dashboard.php?page=eligibility-rules');exit;
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():($e instanceof PDOException&&$e->getCode()==='23000'?'That item or disability rule already exists.':'Unable to update the eligibility rule.');}
}

try{$q=$db->prepare('SELECT dai.*,dt.name disability_name,i.item_name,i.variety FROM disability_aid_items dai JOIN disability_types dt ON dt.id=dai.disability_type_id JOIN inventory_items i ON i.id=dai.item_id WHERE dai.id=:id');$q->execute(['id'=>$ruleId]);$rule=$q->fetch();if(!$rule){http_response_code(404);exit('Eligibility rule not found.');}$disabilities=$db->query("SELECT id,name FROM disability_types WHERE status='active' ORDER BY name")->fetchAll();$aidItems=$db->query('SELECT id,item_name,variety FROM inventory_items ORDER BY item_name,variety')->fetchAll();$q=$db->prepare('SELECT prohibited_item_id FROM disability_item_prohibitions WHERE disability_aid_item_id=:id');$q->execute(['id'=>$ruleId]);$selected=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));}catch(PDOException $e){error_log($e->getMessage());exit('Unable to load the eligibility rule.');}
$years=(int)$rule['restriction_months']>=12&&(int)$rule['restriction_months']%12===0;$period=$years?(int)$rule['restriction_months']/12:(int)$rule['restriction_months'];
?>
<!doctype html><html lang="<?=htmlspecialchars(widmsLanguage(),ENT_QUOTES,'UTF-8')?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edit Eligibility Rule | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css?v=4" rel="stylesheet"></head><body><?php require __DIR__.'/../../includes/subject-officer-sidebar.php';?><div class="admin-shell"><header class="topbar"><h1>Edit Eligibility Rule</h1></header><main class="dashboard-content edit-aid-rule-page"><?php if($errors):?><div class="alert alert-danger"><?=htmlspecialchars(implode(' ',$errors),ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<!-- The dedicated editor keeps all rule details visible without expanding a crowded table row. -->
<div class="edit-rule-heading"><div><a class="edit-rule-back-button" href="dashboard.php?page=eligibility-rules"><span aria-hidden="true">&larr;</span> Back to Eligibility Rules</a><h2><?=htmlspecialchars($rule['item_name'],ENT_QUOTES,'UTF-8')?></h2><p>Review and change every detail associated with this eligibility rule.</p></div><span class="user-status active">Active Rule</span></div>
<form method="post" class="edit-aid-rule-form" id="edit-aid-rule-form"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="rule_id" value="<?=(int)$ruleId?>"><section><h3>Item and Disability</h3><div class="edit-rule-grid"><label>Disability Type<select name="disability_type_id" required><?php foreach($disabilities as $d):?><option value="<?=(int)$d['id']?>" <?=(int)$d['id']===(int)$rule['disability_type_id']?'selected':''?>><?=htmlspecialchars($d['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Item Name<input name="item_name" value="<?=htmlspecialchars($rule['item_name'],ENT_QUOTES,'UTF-8')?>" maxlength="100" required></label><label>Variety / Model<input name="variety" value="<?=htmlspecialchars($rule['variety'],ENT_QUOTES,'UTF-8')?>" maxlength="100"></label></div></section>
<section><h3>Probation Period</h3><div class="edit-rule-grid compact"><label>Period<input type="number" name="restriction_value" min="0" max="100" value="<?=$period?>" required></label><label>Unit<select name="restriction_unit"><option value="months" <?=$years?'':'selected'?>>Months</option><option value="years" <?=$years?'selected':''?>>Years</option></select></label></div></section>
<section><h3>Items Prohibited During Probation</h3><p>The same item is always prohibited automatically. Select any additional items below.</p><div class="edit-prohibited-selector"><?php renderProhibitedItemSelector($aidItems, $selected, (int)$rule['item_id']); ?></div></section>
<div class="edit-rule-actions"><a class="outline-action edit-rule-cancel-button" href="dashboard.php?page=eligibility-rules">Cancel</a><button class="admin-primary-action" type="submit">Save Changes</button></div></form>
<!-- Confirm intentional edits before changing an existing eligibility rule. -->
<dialog class="edit-rule-confirm-dialog" id="edit-rule-confirm-dialog"><div class="edit-rule-confirm-card"><button class="edit-rule-confirm-close" type="button" aria-label="Close">&times;</button><span class="edit-rule-confirm-icon" aria-hidden="true">?</span><h2>Confirm changes</h2><p><span>You are about to update the eligibility details for</span> <strong data-confirm-item-name><?=htmlspecialchars($rule['item_name'],ENT_QUOTES,'UTF-8')?></strong>. <span>Do you want to continue?</span></p><div class="edit-rule-confirm-actions"><button class="edit-rule-dialog-cancel" type="button">Cancel</button><button class="edit-rule-dialog-save" type="button">Save Changes</button></div></div></dialog>
</main></div><script src="assets/js/admin-dashboard.js"></script><script src="assets/js/searchable-multi-select.js?v=3"></script><script src="assets/js/edit-aid-rule.js"></script></body></html>
