<?php
declare(strict_types=1);
requireRole('subject-officer');
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/activity.php';
require_once __DIR__.'/../../includes/prohibited-item-selector.php';
$activePage='item-categories';$errors=[];$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);$db=database();

function itemConfigRedirect(string $message):never{$_SESSION['flash_success']=$message;unset($_SESSION['csrf_token']);header('Location: dashboard.php?page=item-categories');exit;}

// The enhanced item form posts here so the field definition and eligibility rule are saved together.
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='save-item-with-detail'){
 try{
  if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))throw new RuntimeException('Your session expired. Refresh the page and try again.');
  $disability=filter_input(INPUT_POST,'disability_type_id',FILTER_VALIDATE_INT);$name=preg_replace('/\s+/',' ',trim((string)($_POST['item_name']??'')));$variety=preg_replace('/\s+/',' ',trim((string)($_POST['variety']??'')));$period=filter_input(INPUT_POST,'restriction_value',FILTER_VALIDATE_INT);$unit=(string)($_POST['restriction_unit']??'');$blocked=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['prohibited_item_ids']??[])))));$needsDetail=(string)($_POST['beneficiary_detail_required']??'0')==='1';$detailLabel=preg_replace('/\s+/',' ',trim((string)($_POST['beneficiary_detail_label']??'')));$detailType=(string)($_POST['beneficiary_detail_type']??'text');
  if(!$disability||mb_strlen($name)<2||mb_strlen($name)>100)throw new RuntimeException('Select a disability type and enter a valid item name.');if($period===false||$period<0||$period>100||!in_array($unit,['months','years'],true))throw new RuntimeException('Enter a valid probation period and unit.');if($needsDetail&&(mb_strlen($detailLabel)<2||mb_strlen($detailLabel)>100||!in_array($detailType,['text','number'],true)))throw new RuntimeException('Enter a valid beneficiary information field name and type.');$months=$unit==='years'?$period*12:$period;
  $db->beginTransaction();$q=$db->prepare("SELECT id FROM disability_types WHERE id=:id AND status='active'");$q->execute(['id'=>$disability]);if(!$q->fetchColumn())throw new RuntimeException('The selected disability type is unavailable.');$q=$db->prepare("INSERT INTO item_categories(name,distribution_type,returnable,status,created_by) VALUES('Configured Disability Aid','request-based',0,'active',:user) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='active'");$q->execute(['user'=>$_SESSION['user_id']]);$category=(int)$db->lastInsertId();$q=$db->prepare('SELECT id FROM inventory_items WHERE item_name=:name AND variety=:variety LIMIT 1');$q->execute(['name'=>$name,'variety'=>$variety]);$item=(int)$q->fetchColumn();if(!$item){$q=$db->prepare("INSERT INTO inventory_items(item_name,category,variety,quantity,category_id) VALUES(:name,'Configured Disability Aid',:variety,0,:category)");$q->execute(['name'=>$name,'variety'=>$variety,'category'=>$category]);$item=(int)$db->lastInsertId();}
  $q=$db->prepare("INSERT INTO disability_aid_items(disability_type_id,item_id,restriction_months,beneficiary_field_label,beneficiary_field_type,status,created_by) VALUES(:disability,:item,:months,:label,:type,'active',:user) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),restriction_months=VALUES(restriction_months),beneficiary_field_label=VALUES(beneficiary_field_label),beneficiary_field_type=VALUES(beneficiary_field_type),status='active'");$q->execute(['disability'=>$disability,'item'=>$item,'months'=>$months,'label'=>$needsDetail?$detailLabel:null,'type'=>$detailType,'user'=>$_SESSION['user_id']]);$rule=(int)$db->lastInsertId();$db->prepare('DELETE FROM disability_item_prohibitions WHERE disability_aid_item_id=:rule')->execute(['rule'=>$rule]);$add=$db->prepare('INSERT INTO disability_item_prohibitions(disability_aid_item_id,prohibited_item_id) VALUES(:rule,:item)');foreach($blocked as $blockedItem)if($blockedItem!==$item)$add->execute(['rule'=>$rule,'item'=>$blockedItem]);$db->commit();logActivity('Disability Aid Configuration','Configured item eligibility and beneficiary field','ITEM-'.$item);itemConfigRedirect('Aid item configuration saved.');
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to save the aid configuration.';}
}

if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')!=='save-item-with-detail'){
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired. Refresh the page and try again.';
 else try{
  $action=(string)($_POST['action']??'');
  if($action==='add-disability'){
   $name=preg_replace('/\s+/',' ',trim((string)($_POST['disability_name']??'')));
   if(mb_strlen($name)<2||mb_strlen($name)>150)throw new RuntimeException('Enter a disability type between 2 and 150 characters.');
   $q=$db->prepare("INSERT INTO disability_types(name,status,created_by) VALUES(:name,'active',:user) ON DUPLICATE KEY UPDATE status='active'");$q->execute(['name'=>$name,'user'=>$_SESSION['user_id']]);
   logActivity('Disability Aid Configuration','Added disability type',$name);itemConfigRedirect('Disability type saved.');
  }
  if($action==='delete-disability'){
   $disability=filter_input(INPUT_POST,'disability_type_id',FILTER_VALIDATE_INT);if(!$disability)throw new RuntimeException('Select a valid disability type.');
   $db->beginTransaction();$q=$db->prepare('SELECT name FROM disability_types WHERE id=:id FOR UPDATE');$q->execute(['id'=>$disability]);$name=(string)$q->fetchColumn();if($name==='')throw new RuntimeException('The selected disability type no longer exists.');
   // Keep configured rules intact by allowing deletion only for a disability that is not in use.
   $q=$db->prepare('SELECT COUNT(*) FROM disability_aid_items WHERE disability_type_id=:id');$q->execute(['id'=>$disability]);if((int)$q->fetchColumn())throw new RuntimeException('This disability type is used by an eligibility rule. Edit or delete that rule first.');
   $db->prepare('DELETE FROM disability_types WHERE id=:id')->execute(['id'=>$disability]);$db->commit();logActivity('Disability Aid Configuration','Deleted disability type',$name,'deleted');itemConfigRedirect('Disability type removed permanently.');
  }
  if($action==='save-item'){
   $disability=filter_input(INPUT_POST,'disability_type_id',FILTER_VALIDATE_INT);$name=preg_replace('/\s+/',' ',trim((string)($_POST['item_name']??'')));$variety=preg_replace('/\s+/',' ',trim((string)($_POST['variety']??'')));$period=filter_input(INPUT_POST,'restriction_value',FILTER_VALIDATE_INT);$unit=(string)($_POST['restriction_unit']??'');$blocked=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['prohibited_item_ids']??[])))));
   if(!$disability)throw new RuntimeException('Select a disability type.');if(mb_strlen($name)<2||mb_strlen($name)>100)throw new RuntimeException('Enter a valid item name.');if($period===false||$period<0||$period>100)throw new RuntimeException('Enter a valid probation period between 0 and 100.');if(!in_array($unit,['months','years'],true))throw new RuntimeException('Select months or years.');$months=$unit==='years'?$period*12:$period;
   $db->beginTransaction();$q=$db->prepare("SELECT id FROM disability_types WHERE id=:id AND status='active'");$q->execute(['id'=>$disability]);if(!$q->fetchColumn())throw new RuntimeException('The selected disability type is unavailable.');
   // A shared technical category keeps all existing stock workflows compatible.
   $q=$db->prepare("INSERT INTO item_categories(name,distribution_type,returnable,status,created_by) VALUES('Configured Disability Aid','request-based',0,'active',:user) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='active'");$q->execute(['user'=>$_SESSION['user_id']]);$category=(int)$db->lastInsertId();
   $q=$db->prepare('SELECT id FROM inventory_items WHERE item_name=:name AND variety=:variety LIMIT 1');$q->execute(['name'=>$name,'variety'=>$variety]);$item=(int)$q->fetchColumn();if(!$item){$q=$db->prepare("INSERT INTO inventory_items(item_name,category,variety,quantity,category_id) VALUES(:name,'Configured Disability Aid',:variety,0,:category)");$q->execute(['name'=>$name,'variety'=>$variety,'category'=>$category]);$item=(int)$db->lastInsertId();}
   $q=$db->prepare("INSERT INTO disability_aid_items(disability_type_id,item_id,restriction_months,status,created_by) VALUES(:disability,:item,:months,'active',:user) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),restriction_months=VALUES(restriction_months),status='active'");$q->execute(['disability'=>$disability,'item'=>$item,'months'=>$months,'user'=>$_SESSION['user_id']]);$rule=(int)$db->lastInsertId();
   $db->prepare('DELETE FROM disability_item_prohibitions WHERE disability_aid_item_id=:rule')->execute(['rule'=>$rule]);$add=$db->prepare('INSERT INTO disability_item_prohibitions(disability_aid_item_id,prohibited_item_id) VALUES(:rule,:item)');foreach($blocked as $blockedItem)if($blockedItem!==$item)$add->execute(['rule'=>$rule,'item'=>$blockedItem]);
   $db->commit();logActivity('Disability Aid Configuration','Configured item eligibility','ITEM-'.$item);itemConfigRedirect('Aid item and probation rule saved.');
  }
  throw new RuntimeException('Invalid configuration action.');
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to save the aid configuration.';}
}
try{$disabilities=$db->query("SELECT id,name FROM disability_types WHERE status='active' ORDER BY name")->fetchAll();$aidItems=$db->query('SELECT id,item_name,variety FROM inventory_items ORDER BY item_name,variety')->fetchAll();}catch(PDOException $e){error_log($e->getMessage());$disabilities=$aidItems=[];$errors[]='Aid configuration is unavailable. Run the latest database migration.';}
?>
<!doctype html><html lang="<?=htmlspecialchars(widmsLanguage(),ENT_QUOTES,'UTF-8')?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eligibility Rule Builder | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css?v=6" rel="stylesheet"></head><body><?php require __DIR__.'/../../includes/subject-officer-sidebar.php';?><div class="admin-shell"><header class="topbar"><h1>Eligibility Rule Builder</h1></header><main class="dashboard-content master-config-page eligibility-configuration-page">
<?php if($success):?><div class="alert alert-success"><?=htmlspecialchars($success,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($errors):?><div class="alert alert-danger"><?=htmlspecialchars(implode(' ',$errors),ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<!-- Separate disability maintenance from rule creation so each form has its own focused card. -->
<section class="admin-data-card configuration-builder-component disability-builder-component"><div class="admin-data-header"><div><h2>Disability Type Management</h2><p>Create and maintain the disability types used by eligibility rules.</p></div></div><div class="eligibility-build-body">
<form method="post" class="aid-config-compact-form eligibility-build-section"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="add-disability"><fieldset><legend><span aria-hidden="true">&#9855;</span> Add Disability Type</legend><p class="eligibility-section-help">Create a disability before assigning eligible aid items.</p><div class="eligibility-disability-row"><label>Disability Type<input name="disability_name" maxlength="150" required></label><button class="admin-primary-action">Add Disability</button></div></fieldset></form>
<!-- Show current disability types beside creation so officers can safely maintain the available list. -->
<section class="disability-management-card"><div><h3>Manage Disability Types</h3><p>Remove only disability types that are not used by an eligibility rule.</p></div><div class="disability-type-list"><?php if(!$disabilities):?><p class="disability-type-empty">No disability types are available.</p><?php else:foreach($disabilities as $disability):?><div class="disability-type-row"><span><?=htmlspecialchars($disability['name'],ENT_QUOTES,'UTF-8')?></span><form method="post" onsubmit="return confirm('<?=htmlspecialchars(t('Remove this disability type permanently?'),ENT_QUOTES,'UTF-8')?>')"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="delete-disability"><input type="hidden" name="disability_type_id" value="<?=(int)$disability['id']?>"><button class="disability-remove-button" type="submit">Remove</button></form></div><?php endforeach;endif;?></div></section>
</div></section>
<section class="admin-data-card configuration-builder-component aid-item-builder-component"><div class="admin-data-header eligibility-builder-header"><div><h2>Aid Item Rule Builder</h2><p>Select a disability type and build an aid-item eligibility rule.</p></div><a class="outline-action eligibility-register-link" href="dashboard.php?page=eligibility-rules">View Configured Rules</a></div><div class="eligibility-build-body"><form method="post" class="aid-config-form eligibility-build-section"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="save-item"><fieldset><legend><span aria-hidden="true">&#128230;</span> Add Aid Item</legend><p class="eligibility-section-help">Set its probation and optionally prohibit related items.</p><p class="eligibility-required-note"><span aria-hidden="true">*</span> Required fields</p><!-- Present fields sequentially so officers complete each eligibility detail in order. --><div class="aid-config-fields eligibility-aid-fields"><label><span>Disability Type <b class="required-mark" aria-hidden="true">*</b></span><select name="disability_type_id" required aria-required="true"><option value="" selected disabled>Select disability</option><?php foreach($disabilities as $d):?><option value="<?=(int)$d['id']?>"><?=htmlspecialchars($d['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label><span>Item Name <b class="required-mark" aria-hidden="true">*</b></span><input name="item_name" maxlength="100" required aria-required="true"></label><label><span>Variety / Model <small>(Optional)</small></span><input name="variety" maxlength="100"></label><label><span>Probation Period <b class="required-mark" aria-hidden="true">*</b></span><input type="number" name="restriction_value" min="0" max="100" value="0" required aria-required="true"></label><label><span>Period Unit <b class="required-mark" aria-hidden="true">*</b></span><select name="restriction_unit" required aria-required="true"><option value="months">Months</option><option value="years">Years</option></select></label></div><fieldset class="prohibited-items searchable-prohibited-fieldset"><legend>Also prohibit during this period</legend><?php renderProhibitedItemSelector($aidItems, [], null, 'Add the first item now. Other items can be selected from its Edit page later.'); ?></fieldset><div class="aid-config-actions"><button class="admin-primary-action" type="submit">Save Aid Item</button></div></fieldset></form>
</div></section>
</main></div><script src="assets/js/admin-dashboard.js"></script><script src="assets/js/searchable-multi-select.js?v=3"></script></body></html>
