<?php
declare(strict_types=1);
requireRole('store-keeper');
require_once __DIR__ . '/../../config/database.php';
$activePage = 'receipt-history';
$receipts = [];
$error = '';
try {
    $receipts = database()->query('SELECT r.id,r.quantity,r.power,r.total_cost,r.paid_amount,r.balance_amount,r.bill_number,r.payment_status,s.company_name,i.item_name,i.variety FROM stock_receipts r JOIN suppliers s ON s.id=r.supplier_id JOIN inventory_items i ON i.id=r.item_id ORDER BY r.id DESC')->fetchAll();
} catch (PDOException $exception) { error_log($exception->getMessage()); $error = 'Receipt history could not be loaded.'; }
$statusLabels = ['fully-paid'=>'Fully Paid','partially-paid'=>'Partially Paid','unpaid'=>'Outstanding — Not Yet Paid'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Receipt History | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css?v=26" rel="stylesheet"></head>
<body class="store-page store-receipt-history-page"><?php require __DIR__ . '/../../includes/store-keeper-sidebar.php'; ?><div class="admin-shell"><header class="topbar"><h1>Receipt History</h1></header><main class="dashboard-content"><section class="receive-card receipt-history-card"><div class="receive-card-header"><h2>Recorded Aid Receipts</h2><p>Review supplier deliveries, quantities, bills, and payment status.</p></div><?php if ($error !== ''): ?><div class="alert alert-danger m-3"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?><div class="receipt-table-wrap"><table class="receipt-table"><thead><tr><th>Batch ID</th><th>Aid</th><th>Qty</th><th>Supplier</th><th>Bill No</th><th>Total Cost</th><th>Paid</th><th>Balance</th><th>Payment Status</th></tr></thead><tbody><?php if ($receipts === []): ?><tr><td colspan="9" class="empty-table">No receipts recorded yet.</td></tr><?php else: foreach ($receipts as $receipt): ?><tr><td>BAT-<?= str_pad((string)$receipt['id'],4,'0',STR_PAD_LEFT) ?></td><td><?= htmlspecialchars($receipt['item_name'] . ($receipt['variety'] !== '' ? ' (' . $receipt['variety'] . ')' : ''), ENT_QUOTES, 'UTF-8') ?></td><td><?= (int)$receipt['quantity'] ?></td><td><?= htmlspecialchars($receipt['company_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($receipt['bill_number'], ENT_QUOTES, 'UTF-8') ?></td><td>Rs <?= number_format((float)$receipt['total_cost'],2) ?></td><td>Rs <?= number_format((float)$receipt['paid_amount'],2) ?></td><td>Rs <?= number_format((float)$receipt['balance_amount'],2) ?></td><td><span class="payment-badge <?= htmlspecialchars($receipt['payment_status'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($statusLabels[$receipt['payment_status']] ?? $receipt['payment_status'], ENT_QUOTES, 'UTF-8') ?></span></td></tr><?php endforeach; endif; ?></tbody></table></div></section></main></div><script src="assets/js/admin-dashboard.js"></script></body></html>
